//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OborydovanieOtkaz.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccountingEquipmentEntities : DbContext
    {
        public AccountingEquipmentEntities()
            : base("name=AccountingEquipmentEntities")
        {
        }
        private static AccountingEquipmentEntities _context;
        public static AccountingEquipmentEntities GetContext()
        {
            if (_context == null)
                _context = new AccountingEquipmentEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<EquipmentType> EquipmentType { get; set; }
        public virtual DbSet<ProductionSite> ProductionSite { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TechnicalInspection> TechnicalInspection { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
